/**
 * Promotion drafts (DESIGN §3, §8): the L3 → L4 channel.
 *
 * A lesson that has proven itself (`times_seen >= 3`, confidence high) is
 * *proposed* as a skill or project convention. The design keeps the last step
 * human ("必须人审"), so the plugin never writes into `~/.dsh/skills`: it writes a
 * ready-to-move `SKILL.md` draft inside the memory root instead, where it is
 * reviewable and git-tracked. Accepting a proposal is then a copy, not a writing
 * exercise.
 */
import fs from 'node:fs'
import path from 'node:path'
import { log } from '../log.js'
import { assertInsideScope } from '../store/guard.js'
import { writeAtomic } from '../store/export.js'
import type { MemoryRecord, MemoryScope } from '../store/types.js'

/** Directory holding promotion drafts, relative to a memory root. */
export function proposalsDir(scope: MemoryScope): string {
    return path.join(scope.root, 'proposals')
}

/** File a draft lives in, or `undefined` when the scope is unusable. */
export function skillDraftPath(scope: MemoryScope, record: MemoryRecord): string | undefined {
    try {
        const file = path.join(proposalsDir(scope), `${record.id}.SKILL.md`)
        assertInsideScope(scope, file)
        return file
    } catch (error) {
        log('warn', `memory: refusing to draft a skill outside the scope (${(error as Error).message})`)
        return undefined
    }
}

/** Skill name for a promoted lesson: stable, filesystem-safe, prefixed. */
export function skillDraftName(record: MemoryRecord): string {
    const slug = record.id
        .toLowerCase()
        .replace(/[^a-z0-9-]+/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')
    return `mem-${slug === '' ? 'lesson' : slug}`.slice(0, 60)
}

/**
 * The draft itself: host-compatible frontmatter plus the lesson, with its
 * provenance so a reviewer can judge it.
 */
export function renderSkillDraft(record: MemoryRecord, now = new Date()): string {
    const when = record.body.trim().split('\n')[0]?.slice(0, 160) ?? record.title
    return [
        '---',
        `name: ${skillDraftName(record)}`,
        `description: ${JSON.stringify(`${record.title} — apply when: ${when}`)}`,
        'user-invocable: false',
        '---',
        '',
        `# ${record.title}`,
        '',
        record.body.trim(),
        '',
        '---',
        '',
        '> Promotion draft, generated by dsh-memory. Review it, then move it to',
        '> `~/.dsh/skills/<name>/SKILL.md` (or a project `.dsh/skills/`) to make the',
        '> host load it; the lesson itself stays where it is until you demote it.',
        '',
        `provenance: id=${record.id} layer=${record.layer} seen=${record.timesSeen}× confidence=${record.confidence.toFixed(2)} exported=${now.toISOString().slice(0, 10)}`,
        '',
    ].join('\n')
}

/** Write (or refresh) the draft for one promotion candidate. */
export function writeSkillDraft(scope: MemoryScope, record: MemoryRecord, now = new Date()): string | undefined {
    const file = skillDraftPath(scope, record)
    if (file === undefined) return undefined
    try {
        writeAtomic(file, renderSkillDraft(record, now))
        return file
    } catch (error) {
        log('warn', `memory: skill draft write failed for ${record.id}:`, error)
        return undefined
    }
}

/** Remove drafts whose proposal no longer exists (a rejected promotion). */
export function pruneSkillDrafts(scope: MemoryScope, keepIds: readonly string[]): number {
    const dir = proposalsDir(scope)
    if (!fs.existsSync(dir)) return 0
    const keep = new Set(keepIds.map((id) => `${id}.SKILL.md`))
    let removed = 0
    try {
        for (const name of fs.readdirSync(dir)) {
            if (!name.endsWith('.SKILL.md') || keep.has(name)) continue
            const file = path.join(dir, name)
            assertInsideScope(scope, file)
            fs.rmSync(file)
            removed += 1
        }
    } catch (error) {
        log('debug', 'memory: pruning skill drafts failed:', error)
    }
    return removed
}
