/**
 * Promotion drafts (DESIGN §3, §8): the L3 → L4 channel.
 *
 * A lesson that has proven itself (`times_seen >= 3`, confidence high) is
 * *proposed* as a skill or project convention. The design keeps the last step
 * human ("必须人审"), so the plugin writes a ready-to-move `SKILL.md` draft
 * inside the memory root first, where it is reviewable and git-tracked.
 *
 * What stays human is the *decision*, not the copying: nothing here runs on its
 * own, and `installSkillDraft` is only reached through an explicit
 * `memory_consolidate({ acceptProposal })` (or a hand move of the draft file).
 */
import fs from 'node:fs'
import path from 'node:path'
import { log } from '../log.js'
import { isInside } from '../paths.js'
import { assertInsideScope } from '../store/guard.js'
import { writeAtomic } from '../store/export.js'
import type { MemoryRecord, MemoryScope } from '../store/types.js'

/** Directory holding promotion drafts, relative to a memory root. */
export function proposalsDir(scope: MemoryScope): string {
    return path.join(scope.root, 'proposals')
}

/** File a draft lives in, or `undefined` when the scope is unusable. */
export function skillDraftPath(scope: MemoryScope, record: MemoryRecord): string | undefined {
    try {
        const file = path.join(proposalsDir(scope), `${record.id}.SKILL.md`)
        assertInsideScope(scope, file)
        return file
    } catch (error) {
        log('warn', `memory: refusing to draft a skill outside the scope (${(error as Error).message})`)
        return undefined
    }
}

/** Skill name for a promoted lesson: stable, filesystem-safe, prefixed. */
export function skillDraftName(record: MemoryRecord): string {
    const slug = record.id
        .toLowerCase()
        .replace(/[^a-z0-9-]+/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')
    return `mem-${slug === '' ? 'lesson' : slug}`.slice(0, 60)
}

/**
 * The draft itself: host-compatible frontmatter plus the lesson, with its
 * provenance so a reviewer can judge it.
 */
export function renderSkillDraft(record: MemoryRecord, now = new Date()): string {
    const when = record.body.trim().split('\n')[0]?.slice(0, 160) ?? record.title
    return [
        '---',
        `name: ${skillDraftName(record)}`,
        `description: ${JSON.stringify(`${record.title} — apply when: ${when}`)}`,
        'user-invocable: false',
        '---',
        '',
        `# ${record.title}`,
        '',
        record.body.trim(),
        '',
        '---',
        '',
        '> Promotion draft, generated by dsh-memory. Review it, then install it with',
        '> `memory_consolidate({ acceptProposal: "<id>" })` — or move this file to',
        '> `~/.dsh/skills/<name>/SKILL.md` (a project `.dsh/skills/` works too) — to make the',
        '> host load it; the lesson itself stays where it is until you demote it.',
        '',
        `provenance: id=${record.id} layer=${record.layer} seen=${record.timesSeen}× confidence=${record.confidence.toFixed(2)} exported=${now.toISOString().slice(0, 10)}`,
        '',
    ].join('\n')
}

/** Write (or refresh) the draft for one promotion candidate. */
export function writeSkillDraft(scope: MemoryScope, record: MemoryRecord, now = new Date()): string | undefined {
    const file = skillDraftPath(scope, record)
    if (file === undefined) return undefined
    try {
        writeAtomic(file, renderSkillDraft(record, now))
        return file
    } catch (error) {
        log('warn', `memory: skill draft write failed for ${record.id}:`, error)
        return undefined
    }
}

/** Remove drafts whose proposal no longer exists (a rejected promotion). */
export function pruneSkillDrafts(scope: MemoryScope, keepIds: readonly string[]): number {
    const dir = proposalsDir(scope)
    if (!fs.existsSync(dir)) return 0
    const keep = new Set(keepIds.map((id) => `${id}.SKILL.md`))
    let removed = 0
    try {
        for (const name of fs.readdirSync(dir)) {
            if (!name.endsWith('.SKILL.md') || keep.has(name)) continue
            const file = path.join(dir, name)
            assertInsideScope(scope, file)
            fs.rmSync(file)
            removed += 1
        }
    } catch (error) {
        log('debug', 'memory: pruning skill drafts failed:', error)
    }
    return removed
}

/**
 * A host skill name is a single path segment of `[a-z0-9-]`.
 *
 * The name comes out of a rendered draft rather than from a constant, so it is
 * validated *before* any path is built from it: a `..`, a `/`, an uppercase
 * letter or a space must never become a directory under `~/.dsh/skills`.
 */
export function isSafeSkillName(name: string): boolean {
    return name.length <= 64 && /^[a-z0-9][a-z0-9-]*$/.test(name)
}

/** The `name:` frontmatter field of a rendered draft — the name the host loads it under. */
export function skillNameOf(draft: string): string | undefined {
    const match = /^name:[ \t]*(\S+)[ \t]*$/m.exec(draft)
    return match?.[1]
}

export interface SkillInstall {
    action: 'installed' | 'unchanged' | 'conflict' | 'invalid-name' | 'failed'
    /** Absolute target path, present once a usable name came out of the draft. */
    file?: string
    name?: string
    message: string
}

/**
 * Install a reviewed promotion draft as a host skill:
 * `<dshHome>/skills/<name>/SKILL.md`.
 *
 * Only an explicit `acceptProposal` reaches this function, so the human
 * decision stays where DESIGN §3 put it — but the step after it is a copy, not
 * an authoring exercise. Two rules keep the install safe:
 *
 *   - the existing file is never clobbered silently: different content is a
 *     conflict unless the caller passed `overwrite`, because a promoted skill
 *     may be a file somebody wrote by hand;
 *   - a failure (bad name, unwritable directory) is returned as a message, so
 *     the caller can leave the proposal open instead of reporting a promotion
 *     that did not happen.
 */
export function installSkillDraft(home: string, draft: string, options: { overwrite?: boolean } = {}): SkillInstall {
    const name = skillNameOf(draft)
    if (name === undefined) {
        return { action: 'invalid-name', message: 'the draft carries no `name:` frontmatter field, so there is no skill to install' }
    }
    if (!isSafeSkillName(name)) {
        return {
            action: 'invalid-name',
            name,
            message: `refusing skill name "${name}": a host skill name must be one path segment of [a-z0-9-]`,
        }
    }
    const skillsRoot = path.join(home, 'skills')
    const file = path.join(skillsRoot, name, 'SKILL.md')
    // Defence in depth: the name is validated above, but a write outside
    // <home>/skills must be impossible even if that check ever changes.
    if (!isInside(skillsRoot, file)) {
        return { action: 'invalid-name', name, message: `refusing to write outside ${skillsRoot}: ${file}` }
    }
    const existing = readFileIfExists(file)
    if (existing !== undefined && existing !== draft && options.overwrite !== true) {
        return {
            action: 'conflict',
            name,
            file,
            message: `refused: ${file} already exists with different content — review it, then pass overwrite: true to replace it (nothing was written)`,
        }
    }
    if (existing === draft) {
        return { action: 'unchanged', name, file, message: `already installed and identical: ${file}` }
    }
    try {
        writeAtomic(file, draft)
    } catch (error) {
        return { action: 'failed', name, file, message: `cannot write ${file}: ${message(error)}` }
    }
    log('info', `memory: promotion installed as a host skill: ${file}`)
    return {
        action: 'installed',
        name,
        file,
        message: existing === undefined ? `installed: ${file}` : `replaced (overwrite): ${file}`,
    }
}

function readFileIfExists(file: string): string | undefined {
    try {
        return fs.readFileSync(file, 'utf8')
    } catch {
        return undefined
    }
}

function message(error: unknown): string {
    return error instanceof Error ? error.message : String(error)
}
